name: Construction et installation du projet

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Construction du fichier war
      run: mvn -B package --file pom.xml
    - uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        connect_timeout: 10s
        scp: |
          './target/*.war' => /root/
        last_ssh: |
          mv /root/*.war /var/lib/tomcat9/webapps/
